### ISSUE TITLE
Referring to node in secondary instance with path that also exists in primary instance can result in a dependency cycle

### ISSUE THREAD

**Issue by lognaturel** [getodk/javarosa#449]
#### Software versions 
All JR versions

#### Problem description
A useful pattern with the `last-instance` feature is to accumulate values across instances. See [dont-show-options-selected-in-other-instances.xml.txt](https://github.com/opendatakit/javarosa/files/3336913/dont-show-options-selected-in-other-instances.xml.txt) for an example. That means referring to the same reference in the current instance and in the previous instance. JavaRosa incorrectly reports a cycle because `TreeReference`s don't take instance into consideration when compared for equality.

#### Steps to reproduce the problem
Try to parse the form above (e.g. by loading it in Collect). See the crash at https://github.com/opendatakit/javarosa/blob/59611cc0755dfbaf6631866ff15d6a9a516df704/src/main/java/org/javarosa/core/model/IDag.java#L473. The cycle reported involves the `previous_schools` node.

#### Expected behavior
No dependency cycle reported.

**Comment by lognaturel** [comment]
Discovered while answering https://forum.opendatakit.org/t/hide-select-item-if-already-selected/20559

**Comment by lognaturel** [comment]
#450 turned out to have really bad unintended consequences.

**Comment by ggalmazor** [comment]
I'm researching this issue. My first task would be to get the simplest possible form that reproduces the issue. I think I got that with this form:

```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa">
    <h:head>
        <h:title>data</h:title>
        <model>
            <instance>
                <data id="data">
                    <aggregated/>
                    <new-part/>
                </data>
            </instance>
            <instance id="last-saved" src="jr://file/issue_449_last_saved.xml"/>
            <bind nodeset="/data/aggregated" type="string" calculate="concat(instance('last-saved')/data/aggregated , ' ',  /data/new-part)"/>
            <bind nodeset="/data/new-part" type="string"/>
        </model>
    </h:head>
    <h:body>
        <input ref="/data/new-part"/>
    </h:body>
</h:html>
```

This is an example of the `issue_449_last_saved.xml` file:
```xml
<data id="data">
    <aggregated>a b</aggregated>
    <new-part>b</new-part>
</data>
```

I'm getting this error when loading this form in a test:

```
org.javarosa.xform.parse.XFormParseException: Cycle detected in form's relevant and calculation logic!
The following nodes are likely involved in the loop:
/data/aggregated

	at org.javarosa.xform.parse.XFormParser.addMainInstanceToFormDef(XFormParser.java:1940)
	at org.javarosa.xform.parse.XFormParser.parseDoc(XFormParser.java:533)
	at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:388)
	at org.javarosa.xform.parse.XFormParser.parse(XFormParser.java:367)
	at org.javarosa.xform.util.XFormUtils.getFormFromInputStream(XFormUtils.java:98)
	at org.javarosa.xform.util.XFormUtils.getFormFromInputStream(XFormUtils.java:79)
	at org.javarosa.core.test.FormParseInit.init(FormParseInit.java:62)
	at org.javarosa.core.test.FormParseInit.<init>(FormParseInit.java:48)
	at org.javarosa.core.test.Scenario.init(Scenario.java:391)
	at org.javarosa.regression.Issue449Test.name(Issue449Test.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

@lognaturel, would you say this is the same thing we're trying to solve?

**Comment by ggalmazor** [comment]
@lognaturel, could you refresh my memory, please? I've just changed `TreeReference.equals()` and `TreeReference.hashCode()` to consider the `instanceName` into the mix, which makes JavaRosa able to load the form (no cycles detected! :smile:)

No other test breaks because of this change too (including the smoke tests)

Does this sound OK to you?

**Comment by lognaturel** [comment]
Sorry, looks like I didn't write a lot of notes in my rush to revert. The solution we had previously (https://github.com/opendatakit/javarosa/pull/450) broke after serialization and deserialization so that would be a good test to add.

**Comment by ggalmazor** [comment]
The only difference I see between my changes and yours from #450 is that I also implemented a change in the `hashCode()` to consider the instance name, so that map keys get matches correctly (this is what solves the cycle in the DAG, actually).

I can't see any other test breaking due to this, and I'm also able to write this specific test for this issue:

```java
@Test
public void try_to_load_the_form() throws IOException, DeserializationException {
    Path formFile = r("issue_449.xml");
    ReferenceManagerTestUtils.setUpSimpleReferenceManager(formFile.getParent(), "file");
    Scenario scenario = Scenario.init(formFile);

    scenario.answer("/data/new-part", "c");
    assertThat(scenario.answerOf("/data/aggregated"), is(stringAnswer("a b c")));

    Scenario deserialized = scenario.serializeAndDeserializeForm();
    assertThat(deserialized.answerOf("/data/new-part"), is(stringAnswer("c")));
    assertThat(deserialized.answerOf("/data/aggregated"), is(stringAnswer("a b c")));

    deserialized.answer("/data/new-part", "c2");
    assertThat(deserialized.answerOf("/data/aggregated"), is(stringAnswer("a b c2")));
}
```

Does this sound right to you, @lognaturel?

(Again, everything is in https://github.com/ggalmazor/javarosa/commits/issue_449_same_path_in_secondary_instance_DAG_cycle)

**Comment by lognaturel** [comment]
Thanks for looking into this and writing a regression test, @ggalmazor! The test passes because your change to `TreeReference` doesn't do anything, unfortunately. The test `ref.instanceName != null && !ref.instanceName.equals(((TreeReference) o).instanceName)` compares the same reference to itself. Even if `this` were used instead of `ref`, the behavior wouldn't be what we want because it wouldn't detect the case where this reference's instance name is null and the other one is non-null. 

https://github.com/getodk/javarosa/issues/475 describes that what users noticed with the previous attempt at a solution was that constraints didn't work anymore.

**Comment by lognaturel** [comment]
> The test passes because your change to TreeReference doesn't do anything, unfortunately

I apologize, that's not right! There were two sources of problems from the original PR: the missing `hashCode` implementation meant the DAG wasn't built up properly and the fact that references in the primary instance were getting an instance name on deserialization rather than `null` meant that reference comparisons were failing in some cases like constraint evaluation.

So indeed, the addition of the `hashCode` implementation made that specific test pass.
