### ISSUE TITLE
Error evaluating jr:choice-name on select from secondary instance in repeat

### ISSUE THREAD

**Issue by lognaturel** [getodk/javarosa#741]
#### Software versions 
JavaRosa v4.2.1

#### Problem description
```java
    @Test
    public void choice_name_with_indexed_repeat_and_secondary_instance() throws IOException, XFormParser.ParseException {
        Scenario scenario = Scenario.init("Secondary instance choices", html(
            head(
                title("Secondary instance choices"),
                model(
                    mainInstance(t("data id=\"choice-name-bug\"",
                        t("repeat jr:template=\"\"",
                            t("q1")
                        ),
                        t("calc")
                    )),

                    t("instance id=\"list\"",
                        t("root",
                            t("item", t("itextId", "choice-0"), t("name", "1"), t("label", "Choice 0")),
                            t("item", t("itextId", "choice-1"), t("name", "3"), t("label", "Choice 1"))
                        )
                    ),

                    bind("/data/calc").type("string").calculate("jr:choice-name(indexed-repeat(/data/repeat/q1, /data/repeat, 1),'/data/repeat/q1')")
                )
            ),
            body(
                repeat("/data/repeat",
                    select1Dynamic("/data/repeat/q1", "instance('list')/root/item", "name", "jr:itext(itextId)")
                )
            )));

        scenario.next();
        scenario.next();
        scenario.createNewRepeat();
    }

   @Test
    public void choice_name_in_repeat_and_inline_select() throws IOException, XFormParser.ParseException {
        Scenario scenario = Scenario.init("Inline choices", html(
            head(
                title("Inline choices"),
                model(
                    mainInstance(t("data id=\"choice-name-inline\"",
                        t("repeat jr:template=\"\"",
                            t("q1")
                        ),
                        t("calc")
                    )),

                    bind("/data/calc").type("string").calculate("jr:choice-name(indexed-repeat(/data/repeat/q1, /data/repeat, 1),'/data/repeat/q1')")
                )
            ),
            body(
                repeat("/data/repeat",
                    select1("/data/repeat/q1", item("choice0", "Choice0"), item("choice1", "Choice1"))
                )
            )));

        scenario.next();
        scenario.createNewRepeat();
        scenario.next();
        scenario.answer("choice1");
        assertThat(scenario.answerOf("/data/calc"), is(stringAnswer("Choice1")));
    }
```

```java
Error evaluating field 'calc' (/data/calc[1]): error in evaluation of xpath function [choice-name] => java.lang.NullPointerException[null]
java.lang.RuntimeException: Error evaluating field 'calc' (/data/calc[1]): error in evaluation of xpath function [choice-name] => java.lang.NullPointerException[null]
	at org.javarosa.core.model.TriggerableDag.evaluateTriggerable(TriggerableDag.java:560)
	at org.javarosa.core.model.TriggerableDag.doEvaluateTriggerables(TriggerableDag.java:534)
	at org.javarosa.core.model.TriggerableDag.initializeTriggerables(TriggerableDag.java:457)
	at org.javarosa.core.model.TriggerableDag.initializeTriggerables(TriggerableDag.java:440)
	at org.javarosa.core.model.FormDef.initializeTriggerables(FormDef.java:711)
	at org.javarosa.core.model.FormDef.initialize(FormDef.java:1196)
	at org.javarosa.core.test.Scenario.init(Scenario.java:464)
	at org.javarosa.core.test.Scenario.init(Scenario.java:439)
	at org.javarosa.core.model.ChoiceNameTest.choice_name_with_indexed_repeat_and_secondary_instance(ChoiceNameTest.java:126)
	...
Caused by: org.javarosa.core.log.WrappedException: error in evaluation of xpath function [choice-name] => java.lang.NullPointerException[null]
	at org.javarosa.core.model.FormDef$3.eval(FormDef.java:892)
	at org.javarosa.xpath.expr.XPathFuncExpr.evalCustomFunction(XPathFuncExpr.java:544)
	at org.javarosa.xpath.expr.XPathFuncExpr.eval(XPathFuncExpr.java:508)
	at org.javarosa.xpath.XPathConditional.evalRaw(XPathConditional.java:72)
	at org.javarosa.core.model.condition.Recalculate.eval(Recalculate.java:50)
	at org.javarosa.core.model.condition.Triggerable.apply(Triggerable.java:119)
	at org.javarosa.core.model.QuickTriggerable.apply(QuickTriggerable.java:41)
	at org.javarosa.core.model.TriggerableDag.evaluateTriggerable(TriggerableDag.java:558)
	... 51 more
```

#### Steps to reproduce the problem
[choice-name-bug.xlsx](https://github.com/getodk/javarosa/files/13970143/choice-name-bug.xlsx)

#### Expected behavior
No crash

#### Other information 
This call works if the select is inline rather than from a secondary instance. The recent changes to `pyxform` to always produce secondary instances make it show up for existing forms that now fail Validate.

`jr:choice-name(${repeat}[position() = 1]/q1,'${q1}')` fails in the same way so it's not related to `indexed-repeat`.

**Comment by lognaturel** [comment]
Should this be considered a form design issue? The second parameter of `'${q1}'` is ambiguous so that's why it doesn't work for secondary instances. I think it would work as expected with `'/data/repeat[position()=1]/q1'` instead

**Comment by lognaturel** [comment]
I wasn't able to get it to work with a qualified reference as the second parameter to `jr:choice-name` but I'm not sure that's really important. I think we can document that to do this kind of thing you need to have a select outside of the repeat to reference. It can have a relevance of `false()` so that it doesn't change what users see.
